steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ejemplos-ander/github.com/anderfernandez/ejemplo-de-mlops:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ejemplos-ander/github.com/anderfernandez/ejemplo-de-mlops:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'ejemplo-mlops', '--image=gcr.io/ejemplo-mlops/github.com/anderfernandez/ejemplo-de-mlops:$SHORT_SHA', '--region=europe-west1', '--platform=managed']

